# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

armaMatMult <- function(A, B) {
    .Call(`_scJIVE_armaMatMult`, A, B)
}

eigenMatMult <- function(A, B, n_cores) {
    .Call(`_scJIVE_eigenMatMult`, A, B, n_cores)
}

eigenMapMatMult2 <- function(A, B, n_cores) {
    .Call(`_scJIVE_eigenMapMatMult2`, A, B, n_cores)
}

eigenBDCSVD <- function(A, n_cores) {
    .Call(`_scJIVE_eigenBDCSVD`, A, n_cores)
}

eigenSingularValues <- function(A, n_cores) {
    .Call(`_scJIVE_eigenSingularValues`, A, n_cores)
}

